/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfiliRouteImport } from './routes/profili'
import { Route as PlayerRouteImport } from './routes/player'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfiliRoute = ProfiliRouteImport.update({
  id: '/profili',
  path: '/profili',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/player': typeof PlayerRoute
  '/profili': typeof ProfiliRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/player': typeof PlayerRoute
  '/profili': typeof ProfiliRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/player': typeof PlayerRoute
  '/profili': typeof ProfiliRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/player' | '/profili' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/player' | '/profili' | '/settings'
  id: '__root__' | '/player' | '/profili' | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PlayerRoute: typeof PlayerRoute
  ProfiliRoute: typeof ProfiliRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profili': {
      id: '/profili'
      path: '/profili'
      fullPath: '/profili'
      preLoaderRoute: typeof ProfiliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PlayerRoute: PlayerRoute,
  ProfiliRoute: ProfiliRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
